// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_xqvm`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-08-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runner-qkwqxw0vd-project-80034548-concurrent-0`, CPU: `AMD Ryzen 7 3700X 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /ci-cache/target/release/quip-network-node
// benchmark
// pallet
// --pallet
// pallet_xqvm
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/xqvm/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_xqvm`.
pub trait WeightInfo {
	fn store_program(s: u32, ) -> Weight;
	fn execute_base() -> Weight;
}

/// Weights for `pallet_xqvm` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Xqvm::Programs` (r:1 w:1)
	/// Proof: `Xqvm::Programs` (`max_values`: None, `max_size`: Some(65572), added: 68047, mode: `MaxEncodedLen`)
	/// Storage: `Xqvm::ProgramOwner` (r:0 w:1)
	/// Proof: `Xqvm::ProgramOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[3, 65536]`.
	fn store_program(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `69037`
		// Minimum execution time: 15_109_000 picoseconds.
		Weight::from_parts(15_652_330, 69037)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(1_410, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Xqvm::Programs` (r:1 w:0)
	/// Proof: `Xqvm::Programs` (`max_values`: None, `max_size`: Some(65572), added: 68047, mode: `MaxEncodedLen`)
	fn execute_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `66`
		//  Estimated: `69037`
		// Minimum execution time: 16_391_000 picoseconds.
		Weight::from_parts(17_202_000, 69037)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Xqvm::Programs` (r:1 w:1)
	/// Proof: `Xqvm::Programs` (`max_values`: None, `max_size`: Some(65572), added: 68047, mode: `MaxEncodedLen`)
	/// Storage: `Xqvm::ProgramOwner` (r:0 w:1)
	/// Proof: `Xqvm::ProgramOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[3, 65536]`.
	fn store_program(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `69037`
		// Minimum execution time: 15_109_000 picoseconds.
		Weight::from_parts(15_652_330, 69037)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(1_410, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Xqvm::Programs` (r:1 w:0)
	/// Proof: `Xqvm::Programs` (`max_values`: None, `max_size`: Some(65572), added: 68047, mode: `MaxEncodedLen`)
	fn execute_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `66`
		//  Estimated: `69037`
		// Minimum execution time: 16_391_000 picoseconds.
		Weight::from_parts(17_202_000, 69037)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
}
