use codec::Encode;
use pallet_quantum_pow::topology::hash_topology;
use quantum_validation::{
    energy_of_solution_indexed, generate_ising_model_indexed,
    packed::{pack_solution, spin_signs},
    unpack_solution, AllowedValueSpec, MilliValue, TopologyIndex,
};
use serde_json::{json, Value};
use sp_core::{bytes::to_hex, hashing::blake2_256, U256};

/// Stored node and edge order. Labels are sparse and unsorted, and three
/// edges are given with `u > v`, so the hash exercises canonicalization and
/// generation pins stored order.
pub const NODES: [u32; 5] = [42, 7, 1003, 19, 300];
pub const EDGES: [(u32, u32); 5] = [(1003, 7), (19, 42), (300, 42), (7, 19), (1003, 300)];

/// `Set` specs as passed to `register_topology`, out of order. The stored
/// form is sorted, as `canonicalize_spec` does.
pub const H_REGISTERED: [MilliValue; 3] = [1000, -1000, 0];
pub const SPIN_REGISTERED: [MilliValue; 6] = [3000, -1000, 2000, -3000, 1000, -2000];
/// Span 5, which does not divide 2^32, so the modulo reduction is pinned.
pub const J_SPEC: AllowedValueSpec<&[MilliValue]> =
    AllowedValueSpec::IntegerRange { min: -2, max: 2 };

/// Spin magnitudes, one per stored node position. With 3 bits per spin,
/// spin 2 straddles bytes 0 and 1.
pub const SOLUTIONS: [[MilliValue; 5]; 2] = [
    [3000, -1000, 2000, -3000, 1000],
    [-2000, 3000, 1000, 2000, -1000],
];

pub fn nonce() -> U256 {
    U256::from_big_endian(&core::array::from_fn::<u8, 32, _>(|i| i as u8))
}

fn hex(bytes: impl AsRef<[u8]>) -> String {
    to_hex(bytes.as_ref(), false)
}

fn sorted<const N: usize>(mut values: [MilliValue; N]) -> [MilliValue; N] {
    values.sort_unstable();
    values
}

fn spec_json(spec: &AllowedValueSpec<&[MilliValue]>) -> Value {
    match *spec {
        AllowedValueSpec::Set(values) => json!({ "set": values }),
        AllowedValueSpec::IntegerRange { min, max } => {
            json!({ "integerRange": { "min": min, "max": max } })
        }
        AllowedValueSpec::ContinuousRange { min, max } => {
            json!({ "continuousRange": { "min": min, "max": max } })
        }
    }
}

fn edges_json(edges: &[(u32, u32)]) -> Value {
    json!(edges.iter().map(|&(u, v)| [u, v]).collect::<Vec<_>>())
}

pub fn generate_fixture() -> Value {
    let h_registered = AllowedValueSpec::Set(&H_REGISTERED[..]);
    let h_stored_values = sorted(H_REGISTERED);
    let h_stored = AllowedValueSpec::Set(&h_stored_values[..]);
    let spin_registered = AllowedValueSpec::Set(&SPIN_REGISTERED[..]);
    let spin_stored_values = sorted(SPIN_REGISTERED);
    let spin_stored = AllowedValueSpec::Set(&spin_stored_values[..]);

    let topology_hash = hash_topology(&NODES, &EDGES, &h_registered, &J_SPEC, &spin_registered);
    assert_eq!(
        topology_hash,
        hash_topology(&NODES, &EDGES, &h_stored, &J_SPEC, &spin_stored),
        "registered and stored specs must hash identically"
    );

    let mut canonical_nodes = NODES.to_vec();
    canonical_nodes.sort_unstable();
    let mut canonical_edges: Vec<_> = EDGES.iter().map(|&(u, v)| (u.min(v), u.max(v))).collect();
    canonical_edges.sort_unstable();
    let preimage = (
        &canonical_nodes,
        &canonical_edges,
        h_registered.canonical_bytes(),
        J_SPEC.canonical_bytes(),
        spin_registered.canonical_bytes(),
    )
        .encode();
    assert_eq!(
        topology_hash.0,
        blake2_256(&preimage),
        "hash_topology must hash this preimage"
    );

    let index = TopologyIndex::new(&NODES, &EDGES).expect("fixture topology is valid");
    let nonce = nonce();
    let (h, j) = generate_ising_model_indexed(nonce, &NODES, &EDGES, &h_stored, &J_SPEC, &index)
        .expect("fixture generates");

    let solutions: Vec<Value> = SOLUTIONS
        .iter()
        .map(|magnitudes| {
            let packed = pack_solution(magnitudes, &spin_stored).expect("fixture solution packs");
            let decoded =
                unpack_solution(&packed, NODES.len(), &spin_stored).expect("fixture unpacks");
            let spins = spin_signs(&decoded).expect("fixture spins are nonzero");
            let energy = energy_of_solution_indexed(&spins, &h, &EDGES, &j, &index)
                .expect("fixture energy computes");
            json!({
                "packed": hex(&packed),
                "decodedMilli": decoded,
                "spins": spins,
                "energyMilli": energy,
            })
        })
        .collect();

    json!({
        "description": "Ising topology interoperability vector for docs/ising-topology.md. \
            Generated by `cargo run -p pallet-quantum-pow --example \
            generate_ising_topology_fixture -- --write`; do not edit by hand. \
            The hash is computed from the registered specs and equals the hash of the \
            stored specs. Generation, decoding and energy use the stored specs and the \
            stored node and edge order: h[i] belongs to nodes[i], j[k] to edges[k], and \
            spins[i] to nodes[i]. The graph is below the runtime's MinNodes (16), so it \
            cannot be registered on chain; the functions it pins do not check MinNodes.",
        "topology": {
            "nodes": NODES,
            "edges": edges_json(&EDGES),
            "allowedHValues": {
                "registered": spec_json(&h_registered),
                "stored": spec_json(&h_stored),
            },
            "allowedJValues": {
                "registered": spec_json(&J_SPEC),
                "stored": spec_json(&J_SPEC),
            },
            "allowedSpinValues": {
                "registered": spec_json(&spin_registered),
                "stored": spec_json(&spin_stored),
            },
        },
        "hash": {
            "canonicalNodes": canonical_nodes,
            "canonicalEdges": edges_json(&canonical_edges),
            "canonicalBytes": {
                "allowedHValues": hex(h_registered.canonical_bytes()),
                "allowedJValues": hex(J_SPEC.canonical_bytes()),
                "allowedSpinValues": hex(spin_registered.canonical_bytes()),
            },
            "preimage": hex(&preimage),
            "topologyHash": hex(topology_hash.as_bytes()),
        },
        "generation": {
            "nonce": hex(nonce.to_big_endian()),
            "h": h,
            "j": j,
        },
        "solutions": solutions,
    })
}
