// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_miner_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-08-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runner-qkwqxw0vd-project-80034548-concurrent-0`, CPU: `AMD Ryzen 7 3700X 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /ci-cache/target/release/quip-network-node
// benchmark
// pallet
// --pallet
// pallet_miner_registry
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/miner-registry/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_miner_registry`.
pub trait WeightInfo {
	fn set_descriptor() -> Weight;
	fn clear_descriptor() -> Weight;
	fn participate() -> Weight;
}

/// Weights for `pallet_miner_registry` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `MinerRegistry::NodeDescriptors` (r:1 w:1)
	/// Proof: `MinerRegistry::NodeDescriptors` (`max_values`: None, `max_size`: Some(8950), added: 11425, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_descriptor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9084`
		//  Estimated: `12415`
		// Minimum execution time: 98_305_000 picoseconds.
		Weight::from_parts(100_169_000, 12415)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `MinerRegistry::NodeDescriptors` (r:1 w:1)
	/// Proof: `MinerRegistry::NodeDescriptors` (`max_values`: None, `max_size`: Some(8950), added: 11425, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MinerRegistry::LatestParticipation` (r:0 w:1)
	/// Proof: `MinerRegistry::LatestParticipation` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn clear_descriptor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9185`
		//  Estimated: `12415`
		// Minimum execution time: 58_911_000 picoseconds.
		Weight::from_parts(60_314_000, 12415)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `MinerRegistry::NodeDescriptors` (r:1 w:0)
	/// Proof: `MinerRegistry::NodeDescriptors` (`max_values`: None, `max_size`: Some(8950), added: 11425, mode: `MaxEncodedLen`)
	/// Storage: `QuantumPow::QBlockCount` (r:1 w:0)
	/// Proof: `QuantumPow::QBlockCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MinerRegistry::LatestParticipation` (r:1 w:1)
	/// Proof: `MinerRegistry::LatestParticipation` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `MinerRegistry::ParticipantCountByQBlock` (r:1 w:1)
	/// Proof: `MinerRegistry::ParticipantCountByQBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `MinerRegistry::ParticipantsByQBlock` (r:0 w:1)
	/// Proof: `MinerRegistry::ParticipantsByQBlock` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	fn participate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `12415`
		// Minimum execution time: 26_500_000 picoseconds.
		Weight::from_parts(27_541_000, 12415)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `MinerRegistry::NodeDescriptors` (r:1 w:1)
	/// Proof: `MinerRegistry::NodeDescriptors` (`max_values`: None, `max_size`: Some(8950), added: 11425, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_descriptor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9084`
		//  Estimated: `12415`
		// Minimum execution time: 98_305_000 picoseconds.
		Weight::from_parts(100_169_000, 12415)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `MinerRegistry::NodeDescriptors` (r:1 w:1)
	/// Proof: `MinerRegistry::NodeDescriptors` (`max_values`: None, `max_size`: Some(8950), added: 11425, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MinerRegistry::LatestParticipation` (r:0 w:1)
	/// Proof: `MinerRegistry::LatestParticipation` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn clear_descriptor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9185`
		//  Estimated: `12415`
		// Minimum execution time: 58_911_000 picoseconds.
		Weight::from_parts(60_314_000, 12415)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `MinerRegistry::NodeDescriptors` (r:1 w:0)
	/// Proof: `MinerRegistry::NodeDescriptors` (`max_values`: None, `max_size`: Some(8950), added: 11425, mode: `MaxEncodedLen`)
	/// Storage: `QuantumPow::QBlockCount` (r:1 w:0)
	/// Proof: `QuantumPow::QBlockCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MinerRegistry::LatestParticipation` (r:1 w:1)
	/// Proof: `MinerRegistry::LatestParticipation` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `MinerRegistry::ParticipantCountByQBlock` (r:1 w:1)
	/// Proof: `MinerRegistry::ParticipantCountByQBlock` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `MinerRegistry::ParticipantsByQBlock` (r:0 w:1)
	/// Proof: `MinerRegistry::ParticipantsByQBlock` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	fn participate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `12415`
		// Minimum execution time: 26_500_000 picoseconds.
		Weight::from_parts(27_541_000, 12415)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
