// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_validator_admission`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runner-qkwqxw0vd-project-80034548-concurrent-0`, CPU: `AMD Ryzen 7 3700X 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /ci-cache/target/release/quip-network-node
// benchmark
// pallet
// --pallet
// pallet_validator_admission
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/validator-admission/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_validator_admission`.
pub trait WeightInfo {
	fn approve() -> Weight;
	fn remove() -> Weight;
	fn advance() -> Weight;
	fn dispatch_as_root() -> Weight;
}

/// Weights for `pallet_validator_admission` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ValidatorAdmission::Mode` (r:1 w:0)
	/// Proof: `ValidatorAdmission::Mode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorAdmission::Approved` (r:1 w:1)
	/// Proof: `ValidatorAdmission::Approved` (`max_values`: Some(1), `max_size`: Some(1025), added: 1520, mode: `MaxEncodedLen`)
	fn approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1044`
		//  Estimated: `2510`
		// Minimum execution time: 17_854_000 picoseconds.
		Weight::from_parts(18_615_000, 2510)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorAdmission::Mode` (r:1 w:0)
	/// Proof: `ValidatorAdmission::Mode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorAdmission::Approved` (r:1 w:1)
	/// Proof: `ValidatorAdmission::Approved` (`max_values`: Some(1), `max_size`: Some(1025), added: 1520, mode: `MaxEncodedLen`)
	fn remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1076`
		//  Estimated: `2510`
		// Minimum execution time: 17_854_000 picoseconds.
		Weight::from_parts(18_715_000, 2510)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorAdmission::Mode` (r:1 w:1)
	/// Proof: `ValidatorAdmission::Mode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn advance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `62`
		//  Estimated: `1486`
		// Minimum execution time: 11_321_000 picoseconds.
		Weight::from_parts(12_043_000, 1486)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn dispatch_as_root() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_819_000 picoseconds.
		Weight::from_parts(10_480_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ValidatorAdmission::Mode` (r:1 w:0)
	/// Proof: `ValidatorAdmission::Mode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorAdmission::Approved` (r:1 w:1)
	/// Proof: `ValidatorAdmission::Approved` (`max_values`: Some(1), `max_size`: Some(1025), added: 1520, mode: `MaxEncodedLen`)
	fn approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1044`
		//  Estimated: `2510`
		// Minimum execution time: 17_854_000 picoseconds.
		Weight::from_parts(18_615_000, 2510)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorAdmission::Mode` (r:1 w:0)
	/// Proof: `ValidatorAdmission::Mode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorAdmission::Approved` (r:1 w:1)
	/// Proof: `ValidatorAdmission::Approved` (`max_values`: Some(1), `max_size`: Some(1025), added: 1520, mode: `MaxEncodedLen`)
	fn remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1076`
		//  Estimated: `2510`
		// Minimum execution time: 17_854_000 picoseconds.
		Weight::from_parts(18_715_000, 2510)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorAdmission::Mode` (r:1 w:1)
	/// Proof: `ValidatorAdmission::Mode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn advance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `62`
		//  Estimated: `1486`
		// Minimum execution time: 11_321_000 picoseconds.
		Weight::from_parts(12_043_000, 1486)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn dispatch_as_root() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_819_000 picoseconds.
		Weight::from_parts(10_480_000, 0)
	}
}
