// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_quantum_compute_mempool`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-08-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runner-qkwqxw0vd-project-80034548-concurrent-0`, CPU: `AMD Ryzen 7 3700X 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /ci-cache/target/release/quip-network-node
// benchmark
// pallet
// --pallet
// pallet_quantum_compute_mempool
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/quantum-compute-mempool/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_quantum_compute_mempool`.
pub trait WeightInfo {
	fn register_solver() -> Weight;
	fn deregister_solver() -> Weight;
	fn register_job_spec() -> Weight;
	fn propose_job(n: u32, e: u32, b: u32, t: u32, ) -> Weight;
	fn submit_solution(n: u32, e: u32, s: u32, ) -> Weight;
	fn claim_reward() -> Weight;
	fn reclaim_order() -> Weight;
	fn purge_result() -> Weight;
}

/// Weights for `pallet_quantum_compute_mempool` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `QuantumComputeMempool::Solvers` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::Solvers` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	fn register_solver() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41`
		//  Estimated: `3574`
		// Minimum execution time: 14_367_000 picoseconds.
		Weight::from_parts(15_129_000, 3574)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `QuantumComputeMempool::Solvers` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::Solvers` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	fn deregister_solver() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3574`
		// Minimum execution time: 15_690_000 picoseconds.
		Weight::from_parts(16_502_000, 3574)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `QuantumComputeMempool::JobSpecs` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobSpecs` (`max_values`: None, `max_size`: Some(297), added: 2772, mode: `MaxEncodedLen`)
	fn register_job_spec() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `3762`
		// Minimum execution time: 18_324_000 picoseconds.
		Weight::from_parts(19_306_000, 3762)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `QuantumComputeMempool::JobSpecs` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobSpecs` (`max_values`: None, `max_size`: Some(297), added: 2772, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::ProposerOrders` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::ProposerOrders` (`max_values`: None, `max_size`: Some(305), added: 2780, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::NextOrderId` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::NextOrderId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::JobOrders` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::JobOrders` (`max_values`: None, `max_size`: Some(640946), added: 643421, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OpenOrders` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::OpenOrders` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[2, 5000]`.
	/// The range of component `e` is `[1, 50000]`.
	/// The range of component `b` is `[1, 16]`.
	/// The range of component `t` is `[0, 8]`.
	fn propose_job(n: u32, e: u32, _b: u32, _t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `179`
		//  Estimated: `3770`
		// Minimum execution time: 517_172_000 picoseconds.
		Weight::from_parts(523_905_000, 3770)
			// Standard Error: 5_268
			.saturating_add(Weight::from_parts(258_506, 0).saturating_mul(n.into()))
			// Standard Error: 526
			.saturating_add(Weight::from_parts(79_797, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `QuantumComputeMempool::Solvers` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::Solvers` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::JobOrders` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobOrders` (`max_values`: None, `max_size`: Some(640946), added: 643421, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::JobSpecs` (r:1 w:0)
	/// Proof: `QuantumComputeMempool::JobSpecs` (`max_values`: None, `max_size`: Some(297), added: 2772, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OrderSolutions` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::OrderSolutions` (`max_values`: None, `max_size`: Some(100166), added: 102641, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OrderTopSolvers` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::OrderTopSolvers` (`max_values`: None, `max_size`: Some(1305), added: 3780, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[2, 5000]`.
	/// The range of component `e` is `[1, 50000]`.
	/// The range of component `s` is `[1, 20]`.
	fn submit_solution(_n: u32, e: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1912 + e * (12 ±0) + n * (8 ±0)`
		//  Estimated: `644411`
		// Minimum execution time: 2_613_960_000 picoseconds.
		Weight::from_parts(2_634_228_000, 644411)
			// Standard Error: 21_762
			.saturating_add(Weight::from_parts(855_110, 0).saturating_mul(e.into()))
			// Standard Error: 54_794_211
			.saturating_add(Weight::from_parts(1_968_133_886, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `QuantumComputeMempool::JobOrders` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobOrders` (`max_values`: None, `max_size`: Some(640946), added: 643421, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::JobSpecs` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobSpecs` (`max_values`: None, `max_size`: Some(297), added: 2772, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OrderTopSolvers` (r:1 w:0)
	/// Proof: `QuantumComputeMempool::OrderTopSolvers` (`max_values`: None, `max_size`: Some(1305), added: 3780, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:32 w:32)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::Solvers` (r:32 w:32)
	/// Proof: `QuantumComputeMempool::Solvers` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OrderResults` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::OrderResults` (`max_values`: None, `max_size`: Some(2084), added: 4559, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OpenOrders` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::OpenOrders` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5832`
		//  Estimated: `644411`
		// Minimum execution time: 1_708_961_000 picoseconds.
		Weight::from_parts(1_736_874_000, 644411)
			.saturating_add(T::DbWeight::get().reads(67_u64))
			.saturating_add(T::DbWeight::get().writes(68_u64))
	}
	/// Storage: `QuantumComputeMempool::JobOrders` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobOrders` (`max_values`: None, `max_size`: Some(640946), added: 643421, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OpenOrders` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::OpenOrders` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn reclaim_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `322`
		//  Estimated: `644411`
		// Minimum execution time: 46_488_000 picoseconds.
		Weight::from_parts(47_861_000, 644411)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `QuantumComputeMempool::OrderResults` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::OrderResults` (`max_values`: None, `max_size`: Some(2084), added: 4559, mode: `MaxEncodedLen`)
	fn purge_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `278`
		//  Estimated: `5549`
		// Minimum execution time: 17_864_000 picoseconds.
		Weight::from_parts(18_515_000, 5549)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `QuantumComputeMempool::Solvers` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::Solvers` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	fn register_solver() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41`
		//  Estimated: `3574`
		// Minimum execution time: 14_367_000 picoseconds.
		Weight::from_parts(15_129_000, 3574)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `QuantumComputeMempool::Solvers` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::Solvers` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	fn deregister_solver() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3574`
		// Minimum execution time: 15_690_000 picoseconds.
		Weight::from_parts(16_502_000, 3574)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `QuantumComputeMempool::JobSpecs` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobSpecs` (`max_values`: None, `max_size`: Some(297), added: 2772, mode: `MaxEncodedLen`)
	fn register_job_spec() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `3762`
		// Minimum execution time: 18_324_000 picoseconds.
		Weight::from_parts(19_306_000, 3762)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `QuantumComputeMempool::JobSpecs` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobSpecs` (`max_values`: None, `max_size`: Some(297), added: 2772, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::ProposerOrders` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::ProposerOrders` (`max_values`: None, `max_size`: Some(305), added: 2780, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::NextOrderId` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::NextOrderId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::JobOrders` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::JobOrders` (`max_values`: None, `max_size`: Some(640946), added: 643421, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OpenOrders` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::OpenOrders` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[2, 5000]`.
	/// The range of component `e` is `[1, 50000]`.
	/// The range of component `b` is `[1, 16]`.
	/// The range of component `t` is `[0, 8]`.
	fn propose_job(n: u32, e: u32, _b: u32, _t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `179`
		//  Estimated: `3770`
		// Minimum execution time: 517_172_000 picoseconds.
		Weight::from_parts(523_905_000, 3770)
			// Standard Error: 5_268
			.saturating_add(Weight::from_parts(258_506, 0).saturating_mul(n.into()))
			// Standard Error: 526
			.saturating_add(Weight::from_parts(79_797, 0).saturating_mul(e.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `QuantumComputeMempool::Solvers` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::Solvers` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::JobOrders` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobOrders` (`max_values`: None, `max_size`: Some(640946), added: 643421, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::JobSpecs` (r:1 w:0)
	/// Proof: `QuantumComputeMempool::JobSpecs` (`max_values`: None, `max_size`: Some(297), added: 2772, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OrderSolutions` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::OrderSolutions` (`max_values`: None, `max_size`: Some(100166), added: 102641, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OrderTopSolvers` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::OrderTopSolvers` (`max_values`: None, `max_size`: Some(1305), added: 3780, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[2, 5000]`.
	/// The range of component `e` is `[1, 50000]`.
	/// The range of component `s` is `[1, 20]`.
	fn submit_solution(_n: u32, e: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1912 + e * (12 ±0) + n * (8 ±0)`
		//  Estimated: `644411`
		// Minimum execution time: 2_613_960_000 picoseconds.
		Weight::from_parts(2_634_228_000, 644411)
			// Standard Error: 21_762
			.saturating_add(Weight::from_parts(855_110, 0).saturating_mul(e.into()))
			// Standard Error: 54_794_211
			.saturating_add(Weight::from_parts(1_968_133_886, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `QuantumComputeMempool::JobOrders` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobOrders` (`max_values`: None, `max_size`: Some(640946), added: 643421, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::JobSpecs` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobSpecs` (`max_values`: None, `max_size`: Some(297), added: 2772, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OrderTopSolvers` (r:1 w:0)
	/// Proof: `QuantumComputeMempool::OrderTopSolvers` (`max_values`: None, `max_size`: Some(1305), added: 3780, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:32 w:32)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::Solvers` (r:32 w:32)
	/// Proof: `QuantumComputeMempool::Solvers` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OrderResults` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::OrderResults` (`max_values`: None, `max_size`: Some(2084), added: 4559, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OpenOrders` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::OpenOrders` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5832`
		//  Estimated: `644411`
		// Minimum execution time: 1_708_961_000 picoseconds.
		Weight::from_parts(1_736_874_000, 644411)
			.saturating_add(RocksDbWeight::get().reads(67_u64))
			.saturating_add(RocksDbWeight::get().writes(68_u64))
	}
	/// Storage: `QuantumComputeMempool::JobOrders` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::JobOrders` (`max_values`: None, `max_size`: Some(640946), added: 643421, mode: `MaxEncodedLen`)
	/// Storage: `QuantumComputeMempool::OpenOrders` (r:0 w:1)
	/// Proof: `QuantumComputeMempool::OpenOrders` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn reclaim_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `322`
		//  Estimated: `644411`
		// Minimum execution time: 46_488_000 picoseconds.
		Weight::from_parts(47_861_000, 644411)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `QuantumComputeMempool::OrderResults` (r:1 w:1)
	/// Proof: `QuantumComputeMempool::OrderResults` (`max_values`: None, `max_size`: Some(2084), added: 4559, mode: `MaxEncodedLen`)
	fn purge_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `278`
		//  Estimated: `5549`
		// Minimum execution time: 17_864_000 picoseconds.
		Weight::from_parts(18_515_000, 5549)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
