// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_faucet_ops`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runner-qkwqxw0vd-project-80034548-concurrent-0`, CPU: `AMD Ryzen 7 3700X 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /ci-cache/target/release/quip-network-node
// benchmark
// pallet
// --pallet
// pallet_faucet_ops
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/faucet-ops/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_faucet_ops`.
pub trait WeightInfo {
	fn mint() -> Weight;
	fn set_authority() -> Weight;
	fn disable() -> Weight;
}

/// Weights for `pallet_faucet_ops` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `FaucetOps::Authority` (r:1 w:0)
	/// Proof: `FaucetOps::Authority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FaucetOps::State` (r:1 w:0)
	/// Proof: `FaucetOps::State` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EmissionController::FaucetIssued` (r:1 w:1)
	/// Proof: `EmissionController::FaucetIssued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `EmissionController::FaucetBudget` (r:1 w:0)
	/// Proof: `EmissionController::FaucetBudget` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `263`
		//  Estimated: `1517`
		// Minimum execution time: 45_585_000 picoseconds.
		Weight::from_parts(47_168_000, 1517)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `FaucetOps::Authority` (r:0 w:1)
	/// Proof: `FaucetOps::Authority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_824_000 picoseconds.
		Weight::from_parts(8_426_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `FaucetOps::Authority` (r:1 w:0)
	/// Proof: `FaucetOps::Authority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FaucetOps::State` (r:1 w:1)
	/// Proof: `FaucetOps::State` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn disable() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `185`
		//  Estimated: `1517`
		// Minimum execution time: 13_615_000 picoseconds.
		Weight::from_parts(14_357_000, 1517)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `FaucetOps::Authority` (r:1 w:0)
	/// Proof: `FaucetOps::Authority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FaucetOps::State` (r:1 w:0)
	/// Proof: `FaucetOps::State` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EmissionController::FaucetIssued` (r:1 w:1)
	/// Proof: `EmissionController::FaucetIssued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `EmissionController::FaucetBudget` (r:1 w:0)
	/// Proof: `EmissionController::FaucetBudget` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `263`
		//  Estimated: `1517`
		// Minimum execution time: 45_585_000 picoseconds.
		Weight::from_parts(47_168_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `FaucetOps::Authority` (r:0 w:1)
	/// Proof: `FaucetOps::Authority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_824_000 picoseconds.
		Weight::from_parts(8_426_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `FaucetOps::Authority` (r:1 w:0)
	/// Proof: `FaucetOps::Authority` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FaucetOps::State` (r:1 w:1)
	/// Proof: `FaucetOps::State` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn disable() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `185`
		//  Estimated: `1517`
		// Minimum execution time: 13_615_000 picoseconds.
		Weight::from_parts(14_357_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
